version: '3'
services:
  php-app:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    volumes:
#      - ${PWD}:/var/www/html
      - ./html:/var/www/html
    ports:
      - "8080:80"
    network_mode: "sample-network2" # 上で作成したカスタムネットワークの名前を記載する

  dotnet:
    container_name: dotnet
    build:
      context: ./dotnet-docker/samples/aspnetapp
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./asp/source:/source
#      - ./dotnet-docker/samples/aspnetapp/aspnetapp:/source
    ports:
      - "5051:5001"
    network_mode: "sample-network2" # 上で作成したカスタムネットワークの名前を記載する

  db1:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      # MySQLの設定ファイル
      - ./mysql/mysql_conf:/etc/mysql/conf.d
    network_mode: "sample-network2"

networks:
  sample-network2: